version: '3.9'

services:
  service-a:
    build: ./services/service-a
    ports:
      - "5000:5000"
    restart: unless-stopped

  service-b:
    build: ./services/service-b
    ports:
      - "4000:4000"
    restart: unless-stopped
